### PR TITLE
Install header files to include/

### PR DESCRIPTION
**Pull request by yan12125**
Originally all header files are installed to ```/usr``` or ```$HOME/.local``` (If --user specified to setup.py). With this patch these files are installed to ```/usr/include``` or ```$HOME/.local/include```

### CODE REVIEW

**Comment by tdsmith** [comment]
Why does setup.py install header files?

**Comment by yan12125** [comment]
I'm not sure why. The original ```setup.py``` was written by @zachriggle (in 3f347c415eb27d577c4198f71de171943e097c75). What I do is trying not to mess up the system.

**Comment by bwall** [comment]
Yeah, I'm not sure either.

I did a quick test, and it looks like test.py runs fine if the line is commented out.  I might be missing something though.

**Comment by zachriggle** [comment]
No idea.  I was just following a template from somewhere, and it worked.  Presumably it's required for the native library to be built.

**Comment by tdsmith** [comment]
Okay! Yeah, you have to do something to make sure the header files get bundled in the tarball that `setup.py sdist` generates or else they'll be missing at build time when the package is downloaded from pypi. package_data accomplishes that, but package_data stuff gets installed by `setup.py install`, and you don't need the headers to use the extension. MANIFEST.in lets you spec "extra" files that need to be included in the sdist but don't need to be installed. You can see that approach in #14. Thanks for the responses!

**Pull request merged**
